name = "imc-12th"
author = "haneki"
version = "1.9.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bddff1b308a0afdc728dd0f01d45a9d623b1f13680b533af30beead606af9e04"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
