name = "imc-12th"
author = "haneki"
version = "1.9.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dac6c4d5206081fc551dfbb4fac81bdef662f3442c3f883f1a51f39912988a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
